title: 滨海的小村
description: A Little Seaside Village | A Place to Rest in God’s Word
theme: minima

lang: zh-CN
timezone: America/New_York

header_pages:
  - index.md
  - deuteronomy.md
  - about.md

show_excerpts: true

google_analytics: G-Z9X56B9HZM

plugins:
  - jekyll-sitemap
