title: 宁静的小村
description: 圣经默想 · 神学札记 · 信仰随笔
theme: minima

lang: zh-CN
timezone: America/New_York

header_pages:
  - index.md
  - deuteronomy.md
  - about.md

show_excerpts: true

google_analytics: G-Z9X56B9HZM
